version: "3.9"

services:
  jupyterlab:
    build: .
    container_name: ds_jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - .:/app  # Mount current folder
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      jupyter lab
      --ip=0.0.0.0
      --allow-root
      --no-browser
      --NotebookApp.token=''
      --NotebookApp.password=''
